services:
  flask-backend:
    build: ./FlaskBackend

  db:
    build: ./backend/database
    ports:
      - "3306:3306"

  dronehub:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - flask-backend
  
  dashboard:
    build: ./Dashboard
    ports:
      - "80:80"
    environment:
      - PORT=80
    depends_on:
      - dronehub
